name: swim_analyzer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  video_player: ^2.8.6
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  provider: ^6.1.2 # Added provider
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  shared_preferences: ^2.2.3
  pdf: ^3.10.8
  printing: ^5.12.0
  sign_in_with_apple: ^6.1.1
  crypto: ^3.0.3
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  video_thumbnail: ^0.5.6

    #ffmpeg_kit_flutter_new: ^3.1.9
   #Switch to a path dependency for local development
  swim_apps_shared:
    git:
      url: git@github.com:johannesskagius/swim_apps_shared.git
      ref: master
      

  #swim_apps_shared:
  #  path: /Users/johannesskagius/Company/projects/swim_apps_shared/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/detect_5m_marks.tflite

